"""Neural parameter-space LM training with optional pseudo-arclength control.

Every corrected state is generated by a spatial MLP. Automatic differentiation
forms the Jacobian with respect to network weights (and free work coordinate),
never a conventional equilibrium solution used as a network target.
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import torch
from torch.func import functional_call, jacrev

from interface_pinn import ROOT, evaluate, load_inputs, network_from_config, sha256
from analyze_interface_pinn import physical_tangent


def read_neural_branch(directory):
    """Read accepted fields, replacing a coarse suffix with its resumed path."""
    config = json.loads((directory / "run_config.json").read_text())
    rows = json.loads((directory / "states.json").read_text())
    fields = np.load(directory / "fields.npz")["slip_mm"]
    if config.get("prefix_run"):
        prefix_rows, prefix_fields = read_neural_branch(ROOT / config["prefix_run"])
        keep = [i for i, row in enumerate(prefix_rows) if row["control_delta0"] < rows[0]["control_delta0"] - 1e-10]
        rows = [prefix_rows[i] for i in keep] + rows
        fields = np.concatenate((prefix_fields[keep], fields))
    return rows, fields


def continuation_stop(row, config):
    """Name the requested branch event without equating it to measured capacity."""
    if config.get("stop_at_first_instability", False) and row["tangent_min_N_per_mm"] < 0:
        return "negative_load_controlled_tangent"
    if (config.get("stop_at_controlled_instability", False)
            and row["controlled_tangent_min_N_per_mm"] < 0):
        return "negative_work_controlled_tangent"
    if ("maximum_control" in config
            and row["control_delta0"] >= config["maximum_control"]):
        return "requested_work_coordinate_reached"
    return None


class NeuralState:
    def __init__(self, network, physics, law):
        self.network, self.physics, self.law = network, physics, law
        self.layout = [(name, p.shape, p.numel()) for name, p in network.named_parameters()]
        self.size = sum(n for _, _, n in self.layout)
        tp, d0, _, _, _ = law.physical()
        self.dscale = d0.detach() * physics.active.sum().sqrt()
        self.pscale = (tp * physics.area.sum() / abs(physics.direction @ physics.f)).detach()

    def pack(self, control):
        return torch.cat([p.detach().flatten() for p in self.network.parameters()]
                         + [self.physics.f.new_tensor([control])])

    def parameters(self, vector):
        result, offset = {}, 0
        for name, shape, count in self.layout:
            result[name] = vector[offset:offset + count].view(shape)
            offset += count
        return result

    def fields(self, vector):
        return functional_call(self.network, self.parameters(vector),
                               (vector[-1:].reshape(1), self.physics))[0]

    def physical(self, vector):
        d = self.fields(vector)
        p = self.physics
        t = self.law.force(d, p.area)[p.active]
        internal = p.K @ d[p.active] + t
        load = (internal @ p.direction) / (p.direction @ p.f)
        rf = internal - load * p.f
        return d, load, rf, t

    def path(self, vector):
        d, load, _, _ = self.physical(vector)
        return self.scaled_path(d, load)

    def scaled_path(self, d, load):
        return torch.cat((d[self.physics.active] / self.dscale, load[None] / self.pscale))

    @torch.no_grad()
    def install(self, vector):
        for name, p in self.network.named_parameters():
            p.copy_(self.parameters(vector)[name])

    @torch.no_grad()
    def diagnostics(self, vector):
        _, load, rf, t = self.physical(vector)
        scale = torch.maximum(torch.linalg.vector_norm(load * self.physics.f),
                              torch.linalg.vector_norm(t)).clamp(min=1e-20)
        return {"control_delta0": float(vector[-1]), "load_kN": float(load),
                "force_relative": float(torch.linalg.vector_norm(rf) / scale)}


def correct(state, initial, config, log, fixed_control=None, anchor=None, tangent=None, step=None,
            fixed_load=None):
    """Damped Gauss-Newton updates in trainable neural coordinates only."""
    vector = initial.detach().clone()
    if fixed_control is not None:
        vector[-1] = fixed_control
    with torch.no_grad():
        _, _, _, t = state.physical(vector)
        # Fixed for this correction, including all trial evaluations and AD calls.
        energy_scale = (t @ state.physics.C @ t).clamp(min=1e-30).sqrt()

    def residual(v):
        # Fixed work is a prescribed coordinate, not a tradeoff with equilibrium.
        field_vector = v if fixed_control is None else torch.cat((v[:-1], v.new_tensor([fixed_control])))
        d, load, rf, _ = state.physical(field_vector)
        white = rf @ state.physics.chol_C / energy_scale
        if fixed_control is not None:
            control_row = (v[-1] - fixed_control) / max(abs(fixed_control), 0.01)
        elif fixed_load is not None:
            control_row = (load - fixed_load) / max(abs(fixed_load), 1e-5)
        else:
            control_row = ((state.scaled_path(d, load) - anchor) @ tangent - step) / step
        return torch.cat((white, control_row[None]))

    damping = config.get("initial_damping", 1e-5)
    for iteration in range(config["lm_iterations"]):
        r = residual(vector).detach()
        info = state.diagnostics(vector)
        info.update(iteration=iteration, loss=float(r @ r), constraint_error=float(abs(r[-1])), damping=damping)
        log(info)
        if (info["force_relative"] < config["force_tolerance"]
                and info["constraint_error"] < config.get("constraint_tolerance", 1e-7)):
            return vector, True, info
        jacobian = jacrev(residual, chunk_size=config.get("jacobian_chunk", 64))(vector).detach()
        if config.get("column_scaling", False):
            column_norm = torch.linalg.vector_norm(jacobian, dim=0)
            floor = torch.median(column_norm[column_norm > 0]) * 0.01
            parameter_scale = column_norm.clamp(min=floor).reciprocal()
        else:
            parameter_scale = torch.ones_like(vector)
        scaled_jacobian = jacobian * parameter_scale
        gram = scaled_jacobian @ scaled_jacobian.T
        if iteration == 0:
            damping *= float(torch.diagonal(gram).max())
        eye = torch.eye(len(r), device=r.device)
        accepted = False
        for trial in range(14):
            dual = torch.linalg.solve(gram + damping * eye, r)
            update = -parameter_scale * (scaled_jacobian.T @ dual)
            candidate = vector + update
            if candidate[-1] <= 0:
                damping *= 10
                continue
            with torch.no_grad():
                next_r = residual(candidate)
                next_loss = float(next_r @ next_r)
            if np.isfinite(next_loss) and next_loss < info["loss"]:
                vector = candidate.detach()
                damping = max(damping / 3, 1e-18)
                accepted = True
                break
            damping *= 10
        if not accepted:
            info["reason"] = "No decreasing neural-parameter step at tested damping values"
            return vector, False, info
    r = residual(vector).detach()
    info = state.diagnostics(vector)
    info.update(iteration=config["lm_iterations"], loss=float(r @ r), constraint_error=float(abs(r[-1])))
    log(info)
    ok = (info["force_relative"] < config["force_tolerance"]
          and info["constraint_error"] < config.get("constraint_tolerance", 1e-7))
    return vector, ok, info


def run(config_path):
    config = json.loads(config_path.read_text())
    torch.set_default_dtype(torch.float64)
    torch.set_num_threads(config.get("cpu_threads", 4))
    torch.manual_seed(config["seed"])
    physics, law, provenance = load_inputs(config, config["device"])
    network = network_from_config(physics, law, config)
    out = ROOT / config["output_directory"]
    if out.exists():
        raise FileExistsError(f"Preserve existing run: {out}")
    if config.get("initial_checkpoint"):
        source = ROOT / config["initial_checkpoint"]
        saved = torch.load(source, map_location=config["device"], weights_only=True)
        for key in ("operator_sha256", "law_sha256", "law_values"):
            if saved["provenance"][key] != provenance[key]:
                raise ValueError(f"Checkpoint provenance mismatch: {key}")
        for key in ("width", "depth", "fourier_frequencies", "envelope_power"):
            if saved["config"].get(key) != config.get(key):
                raise ValueError(f"Checkpoint architecture mismatch: {key}")
        network.load_initial_state(saved["network"])
        provenance["initial_checkpoint_sha256"] = sha256(source)
    if config.get("fixed_family_checkpoint"):
        network.control_scale.fill_(provenance["fixed_control_scale_mm"])
    out.mkdir(parents=True)
    snapshot = dict(config, source_sha256=sha256(Path(__file__)),
                    physics_source_sha256=sha256(ROOT / "src/interface_pinn.py"))
    (out / "run_config.json").write_text(json.dumps(snapshot, indent=2) + "\n")
    (out / "runner_source.py").write_bytes(Path(__file__).read_bytes())
    (out / "physics_source.py").write_bytes((ROOT / "src/interface_pinn.py").read_bytes())
    state = NeuralState(network, physics, law)
    vector = state.pack(config["fixed_controls"][0])
    accepted_vectors, paths, rows, attempts = [], [], [], []
    start = time.perf_counter()

    def logger(info):
        row = dict(info, attempt=len(attempts), accepted_states=len(rows), seconds=time.perf_counter() - start)
        with (out / "training.jsonl").open("a") as handle:
            handle.write(json.dumps(row) + "\n")
        if info["iteration"] % config.get("log_every", 20) == 0:
            print(json.dumps(row), flush=True)

    def save(v, info, mode):
        state.install(v)
        accepted_vectors.append(v.detach().clone())
        paths.append(state.path(v).detach())
        result = evaluate(network, physics, law, v[-1:])
        row = dict(info, index=len(rows), mode=mode,
                   displacement_relative=float(result["displacement_relative"][0]),
                   hard_control_error_mm=float(result["control_error_mm"][0]))
        if config.get("monitor_tangent", False):
            d = torch.tensor(result["slip_mm"][0], device=physics.f.device)
            stiffness = physical_tangent(physics, law, d)
            values = torch.linalg.eigvalsh(stiffness)
            row["tangent_min_N_per_mm"] = float(values[0])
            row["second_tangent_eigenvalue_N_per_mm"] = float(values[1])
            basis = torch.linalg.qr(physics.f[:, None], mode="complete").Q[:, 1:]
            row["controlled_tangent_min_N_per_mm"] = float(torch.linalg.eigvalsh(basis.T @ stiffness @ basis)[0])
        rows.append(row)
        torch.save({"network": network.state_dict(), "law": law.state_dict(),
                    "config": snapshot, "provenance": provenance, "control_delta0": float(v[-1])},
                   out / f"state_{len(rows)-1:04d}.pt")
        (out / "states.json").write_text(json.dumps(rows, indent=2) + "\n")
        with torch.no_grad():
            fields = torch.stack([state.fields(v) for v in accepted_vectors]).cpu().numpy()
        np.savez_compressed(out / "fields.npz", slip_mm=fields,
                            control=np.array([row["control_delta0"] for row in rows]),
                            load_kN=np.array([row["load_kN"] for row in rows]),
                            force_relative=np.array([row["force_relative"] for row in rows]),
                            xz=physics.xz.cpu().numpy())
        print(json.dumps(dict(event="state_accepted", **row)), flush=True)

    failure, stop_reason = None, None
    for control in config["fixed_controls"]:
        vector, ok, info = correct(state, vector, config, logger, fixed_control=control)
        attempts.append(dict(info, accepted=ok, mode="fixed_work"))
        if not ok:
            failure = "Fixed-work neural correction did not meet residual tolerances"
            break
        save(vector, info, "fixed_work")
        stop_reason = continuation_stop(rows[-1], config)
        if stop_reason:
            break
    if not failure and not stop_reason:
        for load in config.get("fixed_loads_kN", []):
            vector, ok, info = correct(state, vector, config, logger, fixed_load=load)
            attempts.append(dict(info, accepted=ok, mode="fixed_load", target_load_kN=load))
            if not ok:
                failure = "Load-controlled neural correction did not meet residual tolerances"
                break
            save(vector, dict(info, target_load_kN=load), "fixed_load")
            stop_reason = continuation_stop(rows[-1], config)
            if stop_reason:
                break
    if not failure and not stop_reason and config.get("arclength_steps", 0):
        if len(paths) < 2:
            raise ValueError("Arclength requires two accepted neural states")
        step = config["arclength_step"]
        for _ in range(config["arclength_steps"]):
            tangent = paths[-1] - paths[-2]
            distance = torch.linalg.vector_norm(tangent)
            tangent = tangent / distance
            # Network weights are nonunique coordinates: their secant need not
            # predict a nearby field. Retain the last weights and predict only q;
            # the physical field/load secant defines the corrector constraint.
            while True:
                predictor = accepted_vectors[-1].clone()
                predictor[-1] += (step / distance) * (accepted_vectors[-1][-1] - accepted_vectors[-2][-1])
                vector, ok, info = correct(state, predictor, config, logger,
                                           anchor=paths[-1], tangent=tangent, step=step)
                if ok:
                    increment = state.path(vector).detach() - paths[-1]
                    ratio = float(increment.norm() / step)
                    info["arclength_chord_ratio"] = ratio
                    if ratio > config.get("maximum_chord_ratio", 2.0):
                        ok = False
                        info["reason"] = "Corrected state is too far from the local arclength predictor"
                attempts.append(dict(info, accepted=ok, mode="arclength", step=step))
                minimum = config.get("minimum_arclength_step", step)
                if ok or step <= minimum:
                    break
                step = max(step / 2, minimum)
            if not ok:
                failure = "Arclength neural correction did not meet residual tolerances"
                break
            save(vector, info, "arclength")
            stop_reason = continuation_stop(rows[-1], config)
            if stop_reason:
                break
            if info["iteration"] < 12:
                step = min(step * 1.25, config.get("maximum_arclength_step", config["arclength_step"]))
    metrics = {"kind": "neural_parameter_lm_continuation", "status": "needs_refinement" if failure else "completed",
               "stop_reason": stop_reason,
               "failure": failure, "accepted_states": len(rows), "attempts": attempts,
               "elapsed_seconds": time.perf_counter() - start, "provenance": provenance,
               "network_parameter_count": state.size, "force_tolerance": config["force_tolerance"],
               "scope": "Fixed constitutive law; no inverse fit, solution targets or reference solver comparison."}
    # A failed correction remains an explicitly unaccepted candidate for diagnosis.
    state.install(vector)
    torch.save({"network": network.state_dict(), "law": law.state_dict(),
                "config": snapshot, "provenance": provenance, "accepted": failure is None,
                "control_delta0": float(vector[-1])}, out / "final_candidate.pt")
    (out / "metrics.json").write_text(json.dumps(metrics, indent=2) + "\n")
    print(json.dumps({k: v for k, v in metrics.items() if k not in ("provenance", "attempts")}), flush=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    run(parser.parse_args().config)
